### ISSUE TITLE
Random installation failures

### ISSUE THREAD

**Issue by Numbluk** [appsignal/rdkafka-ruby#42]
I was attempting to install `rdkafka-ruby` with `gem install rdkafka -v '0.3.5'`. It failed several times in a row with:

```
Building native extensions. This could take a while...
ERROR:  Error installing rdkafka:
	ERROR: Failed to build gem native extension.

    current directory: /home/lukas/.rvm/gems/ruby-2.5.0/gems/rdkafka-0.3.5/ext
/usr/share/rvm/rubies/ruby-2.5.0/bin/ruby -rrubygems /home/lukas/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake RUBYARCHDIR=/home/lukas/.rvm/gems/ruby-2.5.0/extensions/x86_64-linux/2.5.0/rdkafka-0.3.5 RUBYLIBDIR=/home/lukas/.rvm/gems/ruby-2.5.0/extensions/x86_64-linux/2.5.0/rdkafka-0.3.5
2 retrie(s) left for v0.11.3.tar.gz
1 retrie(s) left for v0.11.3.tar.gz
0 retrie(s) left for v0.11.3.tar.gz
nil can't be coerced into Integer
Extracting v0.11.3.tar.gz into tmp/x86_64-linux-gnu/ports/librdkafka/0.11.3... ERROR, review '/home/lukas/.rvm/gems/ruby-2.5.0/gems/rdkafka-0.3.5/ext/tmp/x86_64-linux-gnu/ports/librdkafka/0.11.3/extract.log' to see what happened. Last lines are:
========================================================================
tar (child): ports/archives/v0.11.3.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
========================================================================
rake aborted!
Failed to complete extract task
/home/lukas/.rvm/gems/ruby-2.5.0/gems/mini_portile2-2.2.0/lib/mini_portile2/mini_portile.rb:400:in `block in execute'
/home/lukas/.rvm/gems/ruby-2.5.0/gems/mini_portile2-2.2.0/lib/mini_portile2/mini_portile.rb:371:in `chdir'
/home/lukas/.rvm/gems/ruby-2.5.0/gems/mini_portile2-2.2.0/lib/mini_portile2/mini_portile.rb:371:in `execute'
/home/lukas/.rvm/gems/ruby-2.5.0/gems/mini_portile2-2.2.0/lib/mini_portile2/mini_portile.rb:365:in `extract_file'
/home/lukas/.rvm/gems/ruby-2.5.0/gems/mini_portile2-2.2.0/lib/mini_portile2/mini_portile.rb:61:in `block in extract'
/home/lukas/.rvm/gems/ruby-2.5.0/gems/mini_portile2-2.2.0/lib/mini_portile2/mini_portile.rb:60:in `each'
/home/lukas/.rvm/gems/ruby-2.5.0/gems/mini_portile2-2.2.0/lib/mini_portile2/mini_portile.rb:60:in `extract'
/home/lukas/.rvm/gems/ruby-2.5.0/gems/mini_portile2-2.2.0/lib/mini_portile2/mini_portile.rb:150:in `cook'
/home/lukas/.rvm/gems/ruby-2.5.0/gems/rdkafka-0.3.5/ext/Rakefile:10:in `block in <top (required)>'
/home/lukas/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<main>'
Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /home/lukas/.rvm/gems/ruby-2.5.0/gems/rdkafka-0.3.5 for inspection.
Results logged to /home/lukas/.rvm/gems/ruby-2.5.0/extensions/x86_64-linux/2.5.0/rdkafka-0.3.5/gem_make.out
```

Out of the blue it ended up working with the same command:

```
gem install rdkafka -v '0.3.5'
Building native extensions. This could take a while...
Successfully installed rdkafka-0.3.5
Parsing documentation for rdkafka-0.3.5
Installing ri documentation for rdkafka-0.3.5
Done installing documentation for rdkafka after 0 seconds
1 gem installed
```

It may or may not be worth noting that I'm running elementary OS 0.4.1 Loki (Ubuntu).

**Comment by will-clarke** [comment]
I also had this problem on a mac
(`tar (child): ports/archives/v0.11.3.tar.gz: Cannot open: No such file or directory`)
 which I also solved by just retrying it.. 🤔 

Any ideas on what could be going on?

**Comment by thijsc** [comment]
It downloads the rdkafka release from GitHub. Probably that was unreachable for you. I'll see if it's possible to get miniportile to give a more a clear error message.
