### ISSUE TITLE
No provider for SASL mechanism GSSAPI

### ISSUE THREAD

**Issue by fyery-chen** [appsignal/rdkafka-ruby#52]
The ruby script is like this:
```ruby
require 'rdkafka'

config = {
        :"bootstrap.servers" => "192.168.0.238:9092" ,
        :"security.protocol" => "SASL_PLAINTEXT" ,
        :"sasl.mechanisms"   => "GSSAPI" ,
        :"sasl.kerberos.principal" => "kafka/kafka.com@RANCHER.COM" ,
        :"sasl.kerberos.keytab" => "/fluentd/etc/ssl/project_c-gwqnp_project-4nsmt_kafka.keytab" ,
}

rdkafka = Rdkafka::Config.new(config)
producer = rdkafka.producer
producer.produce(topic: "test", payload: "Hello World!")
```
And when I exec this script, some errors occured as below,
```
root@fluentd-t9nqb:/fluentd/etc/ssl# ruby ~/test.rb
Traceback (most recent call last):
        2: from /root/test.rb:12:in `<main>'
        1: from /var/lib/gems/2.5.0/gems/rdkafka-0.4.1/lib/rdkafka/config.rb:114:in `producer'
/var/lib/gems/2.5.0/gems/rdkafka-0.4.1/lib/rdkafka/config.rb:164:in `native_kafka': No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN (Rdkafka::Config::ClientCreationError)
```
So I need some help for this.

**Comment by thijsc** [comment]
Looks like SASL isn't built by default. You can change that by adding the relevant configuration option here: https://github.com/appsignal/rdkafka-ruby/blob/master/ext/Rakefile#L28

Pull request for this would be very welcome. We don't use SASL ourselves so it's a bit hard to test for me.

**Comment by fyery-chen** [comment]
@thijsc If I have added the relevant configuration option here, how to rebuild it?

**Comment by thijsc** [comment]
Instructions are here: https://github.com/appsignal/rdkafka-ruby#development

**Comment by thijsc** [comment]
Closing for now, feel free to reopen!

**Comment by clutonik** [comment]
@fyery-chen were you able to get GSSAPI mechanism working ?
