### ISSUE TITLE
Building Native Extensions Fails on Alpine 3.8

### ISSUE THREAD

**Issue by MissingHandle** [appsignal/rdkafka-ruby#87]
Terminal Output:

```
bash-4.4$ gem install rdkafka --version="0.6.0"
Building native extensions. This could take a while...
/usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /usr/local/bundle in PATH, mode 040777
ERROR:  Error installing rdkafka:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/rdkafka-0.6.0/ext
/usr/bin/ruby -rrubygems /usr/local/bundle/gems/rake-12.3.2/exe/rake RUBYARCHDIR=/usr/local/bundle/extensions/x86_64-linux/2.5.0/rdkafka-0.6.0 RUBYLIBDIR=/usr/local/bundle/extensions/x86_64-linux/2.5.0/rdkafka-0.6.0
/usr/local/bundle/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:351: warning: Insecure world writable dir /usr/local/bundle in PATH, mode 040777

Extracting v1.1.0 into tmp/x86_64-alpine-linux-musl/ports/librdkafka/1.1.0... OK
Running 'configure' for librdkafka 1.1.0... OK
Running 'compile' for librdkafka 1.1.0... ERROR, review '/usr/local/bundle/gems/rdkafka-0.6.0/ext/tmp/x86_64-alpine-linux-musl/ports/librdkafka/1.1.0/compile.log' to see what happened. Last lines are:
========================================================================
Creating static library librdkafka++.a
ar rcs librdkafka++.a RdKafka.o ConfImpl.o HandleImpl.o ConsumerImpl.o ProducerImpl.o KafkaConsumerImpl.o TopicImpl.o TopicPartitionImpl.o MessageImpl.o HeadersImpl.o QueueImpl.o MetadataImpl.o
Creating librdkafka++.so symlink
rm -f "librdkafka++.so" && ln -s "librdkafka++.so.1" "librdkafka++.so"
Generating pkg-config file rdkafka++.pc
Generating pkg-config file rdkafka++-static.pc
Checking librdkafka++ integrity
librdkafka++.so.1              OK
librdkafka++.a                 OK
make[1]: Leaving directory '/usr/local/bundle/gems/rdkafka-0.6.0/ext/tmp/x86_64-alpine-linux-musl/ports/librdkafka/1.1.0/librdkafka-1.1.0/src-cpp'
make -C examples
make[1]: Entering directory '/usr/local/bundle/gems/rdkafka-0.6.0/ext/tmp/x86_64-alpine-linux-musl/ports/librdkafka/1.1.0/librdkafka-1.1.0/examples'
gcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align  -I../src rdkafka_example.c -o rdkafka_example  \
	../src/librdkafka.a -lm -lssl  -lcrypto  -L/lib -lz  -ldl -lpthread -lrt -lpthread -lrt
../src/librdkafka.a(rdkafka_ssl.o): In function `rd_kafka_transport_ssl_set_endpoint_id':
/usr/local/bundle/gems/rdkafka-0.6.0/ext/tmp/x86_64-alpine-linux-musl/ports/librdkafka/1.1.0/librdkafka-1.1.0/src/rdkafka_ssl.c:429: undefined reference to `SSL_set1_host'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:18: rdkafka_example] Error 1
make[1]: Leaving directory '/usr/local/bundle/gems/rdkafka-0.6.0/ext/tmp/x86_64-alpine-linux-musl/ports/librdkafka/1.1.0/librdkafka-1.1.0/examples'
make: *** [Makefile:42: examples] Error 2
========================================================================
rake aborted!
Failed to complete compile task
/usr/local/bundle/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:402:in `block in execute'
/usr/local/bundle/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in `chdir'
/usr/local/bundle/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in `execute'
/usr/local/bundle/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:115:in `compile'
/usr/local/bundle/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:154:in `cook'
/usr/local/bundle/gems/rdkafka-0.6.0/ext/Rakefile:36:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<main>'
Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/rdkafka-0.6.0 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.5.0/rdkafka-0.6.0/gem_make.out
```
[gem_make.out.txt](https://github.com/appsignal/rdkafka-ruby/files/3580991/gem_make.out.txt)
[compile.log.txt](https://github.com/appsignal/rdkafka-ruby/files/3581041/compile.log.txt)

**Comment by MissingHandle** [comment]
I figure this has something to do with dynamic vs static linking when compiling, but have no idea what exactly to statically link / what commands to run to accomplish that.

Can share the top of the docker file:

```
FROM alpine:3.8

LABEL maintainer "<ommitting>"

ENV BUILD_PACKAGES build-base curl-dev ruby-dev postgresql-dev libc-dev linux-headers
ENV DEV_PACKAGES bash \
                 ca-certificates \
                 curl \
                 git \
                 libffi-dev \
                 libsodium \
                 libstdc++ \
                 libxml2-dev \
                 libxslt-dev \
                 openssl \
                 postgresql \
                 ruby-full \
                 tzdata \
                 yaml \
                 yaml-dev \
                 zlib-dev \
                 xvfb \
                 ttf-freefont \
                 fontconfig \
                 dbus \
                 qt5-qtbase-dev \
                 qt5-qtwebkit-dev \
                 qt5-qtsvg-dev \
                 qt5-qtxmlpatterns-dev

# Install glibc so we can run prism
# https://github.com/sgerrand/alpine-pkg-glibc
# Install prism
# NOTE V2.0.0 is in alpha
RUN apk update && apk upgrade && apk add --update $DEV_PACKAGES && \
    update-ca-certificates && \
\
    curl -o /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/2.25-r0/sgerrand.rsa.pub && \
    curl -L -O https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk && \
    apk add glibc-2.25-r0.apk

# ... goes on with other stuff that I don't believe is relevant
```

**Comment by MissingHandle** [comment]
Good news for y'all bad for me.  This is not an appsignal issue but a local issue I have.  attempt at a minimal docker file on which gem install succeeds:

```
FROM alpine:3.8.4

LABEL maintainer "rdkafka-install-example"

ENV BUILD_PACKAGES build-base ruby-dev
ENV DEV_PACKAGES bash

RUN apk update && apk upgrade && apk add --update $DEV_PACKAGES

RUN apk add --update $BUILD_PACKAGES

RUN apk add librdkafka-dev
RUN gem install --no-ri --no-rdoc rdkafka  --version="0.6.0"
```

sincerely, denverCoder10
